require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OrderToWarehousesController do

  # This should return the minimal set of attributes required to create a valid
  # OrderToWarehouse. As you add validations to OrderToWarehouse, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {:order_status => "waiting",
      :store_id => 1,
      :warehouse_id => 1}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrderToWarehousesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all order_to_warehouses as @order_to_warehouses" do
      order_to_warehouse = OrderToWarehouse.create! valid_attributes
      get :index, {}
      assigns(:order_to_warehouses).should eq([order_to_warehouse])
    end
  end

  describe "GET show" do
    it "assigns the requested order_to_warehouse as @order_to_warehouse" do
      order_to_warehouse = OrderToWarehouse.create! valid_attributes
      get :show, {:id => order_to_warehouse.to_param}, valid_session
      assigns(:order_to_warehouse).should eq(order_to_warehouse)
    end
  end

  describe "GET new" do
    it "assigns a new order_to_warehouse as @order_to_warehouse" do
      get :new, {}, valid_session
      assigns(:order_to_warehouse).should be_a_new(OrderToWarehouse)
    end
  end

  describe "GET edit" do
    it "assigns the requested order_to_warehouse as @order_to_warehouse" do
      order_to_warehouse = OrderToWarehouse.create! valid_attributes
      get :edit, {:id => order_to_warehouse.to_param}, valid_session
      assigns(:order_to_warehouse).should eq(order_to_warehouse)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OrderToWarehouse" do
        expect {
          post :create, {:order_to_warehouse => valid_attributes}, valid_session
        }.to change(OrderToWarehouse, :count).by(1)
      end

      it "assigns a newly created order_to_warehouse as @order_to_warehouse" do
        post :create, {:order_to_warehouse => valid_attributes}, valid_session
        assigns(:order_to_warehouse).should be_a(OrderToWarehouse)
        assigns(:order_to_warehouse).should be_persisted
      end

      it "redirects to the created order_to_warehouse" do
        post :create, {:order_to_warehouse => valid_attributes}, valid_session
        response.should redirect_to(OrderToWarehouse.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved order_to_warehouse as @order_to_warehouse" do
        # Trigger the behavior that occurs when invalid params are submitted
        OrderToWarehouse.any_instance.stub(:save).and_return(false)
        post :create, {:order_to_warehouse => {}}, valid_session
        assigns(:order_to_warehouse).should be_a_new(OrderToWarehouse)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OrderToWarehouse.any_instance.stub(:save).and_return(false)
        post :create, {:order_to_warehouse => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested order_to_warehouse" do
        order_to_warehouse = OrderToWarehouse.create! valid_attributes
        # Assuming there are no other order_to_warehouses in the database, this
        # specifies that the OrderToWarehouse created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OrderToWarehouse.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => order_to_warehouse.to_param, :order_to_warehouse => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested order_to_warehouse as @order_to_warehouse" do
        order_to_warehouse = OrderToWarehouse.create! valid_attributes
        put :update, {:id => order_to_warehouse.to_param, :order_to_warehouse => valid_attributes}, valid_session
        assigns(:order_to_warehouse).should eq(order_to_warehouse)
      end

      it "redirects to the order_to_warehouse" do
        order_to_warehouse = OrderToWarehouse.create! valid_attributes
        put :update, {:id => order_to_warehouse.to_param, :order_to_warehouse => valid_attributes}, valid_session
        response.should redirect_to(order_to_warehouse)
      end
    end

    describe "with invalid params" do
      it "assigns the order_to_warehouse as @order_to_warehouse" do
        order_to_warehouse = OrderToWarehouse.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OrderToWarehouse.any_instance.stub(:save).and_return(false)
        put :update, {:id => order_to_warehouse.to_param, :order_to_warehouse => {}}, valid_session
        assigns(:order_to_warehouse).should eq(order_to_warehouse)
      end

      it "re-renders the 'edit' template" do
        order_to_warehouse = OrderToWarehouse.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OrderToWarehouse.any_instance.stub(:save).and_return(false)
        put :update, {:id => order_to_warehouse.to_param, :order_to_warehouse => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested order_to_warehouse" do
      order_to_warehouse = OrderToWarehouse.create! valid_attributes
      expect {
        delete :destroy, {:id => order_to_warehouse.to_param}, valid_session
      }.to change(OrderToWarehouse, :count).by(-1)
    end

    it "redirects to the order_to_warehouses list" do
      order_to_warehouse = OrderToWarehouse.create! valid_attributes
      delete :destroy, {:id => order_to_warehouse.to_param}, valid_session
      response.should redirect_to(order_to_warehouses_url)
    end
  end

end
