require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ShelfProductInfosController do

  # This should return the minimal set of attributes required to create a valid
  # ShelfProductInfo. As you add validations to ShelfProductInfo, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {quantity: 1, product_id: 1, shelf_id: 1}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ShelfProductInfosController. Be sure to keep this updated too.
  def valid_session
    {:shelf_id => 1}
  end

  describe "GET index" do
    it "assigns all shelf_product_infos as @shelf_product_infos" do
      shelf_product_info = ShelfProductInfo.create! valid_attributes
      get :index, {}
      assigns(:shelf_product_infos).should eq([shelf_product_info])
    end
  end

  describe "GET show" do
    it "assigns the requested shelf_product_info as @shelf_product_info" do
      shelf_product_info = ShelfProductInfo.create! valid_attributes
      get :show, {:id => shelf_product_info.to_param}, valid_session
      assigns(:shelf_product_info).should eq(shelf_product_info)
    end
  end

  describe "GET new" do
    it "assigns a new shelf_product_info as @shelf_product_info" do
      get :new, {}, valid_session
      assigns(:shelf_product_info).should be_a_new(ShelfProductInfo)
    end
  end

  describe "GET edit" do
    it "assigns the requested shelf_product_info as @shelf_product_info" do
      shelf_product_info = ShelfProductInfo.create! valid_attributes
      get :edit, {:id => shelf_product_info.to_param}, valid_session
      assigns(:shelf_product_info).should eq(shelf_product_info)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ShelfProductInfo" do
        expect {
          post :create, {:shelf_product_info => valid_attributes}, valid_session
        }.to change(ShelfProductInfo, :count).by(1)
      end

      it "assigns a newly created shelf_product_info as @shelf_product_info" do
        post :create, {:shelf_product_info => valid_attributes}, valid_session
        assigns(:shelf_product_info).should be_a(ShelfProductInfo)
        assigns(:shelf_product_info).should be_persisted
      end

      it "redirects to the created shelf_product_info" do
        post :create, {:shelf_product_info => valid_attributes}, valid_session
        response.should redirect_to(ShelfProductInfo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved shelf_product_info as @shelf_product_info" do
        # Trigger the behavior that occurs when invalid params are submitted
        ShelfProductInfo.any_instance.stub(:save).and_return(false)
        post :create, {:shelf_product_info => {}}, valid_session
        assigns(:shelf_product_info).should be_a_new(ShelfProductInfo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ShelfProductInfo.any_instance.stub(:save).and_return(false)
        post :create, {:shelf_product_info => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested shelf_product_info" do
        shelf_product_info = ShelfProductInfo.create! valid_attributes
        # Assuming there are no other shelf_product_infos in the database, this
        # specifies that the ShelfProductInfo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ShelfProductInfo.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => shelf_product_info.to_param, :shelf_product_info => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested shelf_product_info as @shelf_product_info" do
        shelf_product_info = ShelfProductInfo.create! valid_attributes
        put :update, {:id => shelf_product_info.to_param, :shelf_product_info => valid_attributes}, valid_session
        assigns(:shelf_product_info).should eq(shelf_product_info)
      end

      it "redirects to the shelf_product_info" do
        shelf_product_info = ShelfProductInfo.create! valid_attributes
        put :update, {:id => shelf_product_info.to_param, :shelf_product_info => valid_attributes}, valid_session
        response.should redirect_to(shelf_product_info)
      end
    end

    describe "with invalid params" do
      it "assigns the shelf_product_info as @shelf_product_info" do
        shelf_product_info = ShelfProductInfo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ShelfProductInfo.any_instance.stub(:save).and_return(false)
        put :update, {:id => shelf_product_info.to_param, :shelf_product_info => {}}, valid_session
        assigns(:shelf_product_info).should eq(shelf_product_info)
      end

      it "re-renders the 'edit' template" do
        shelf_product_info = ShelfProductInfo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ShelfProductInfo.any_instance.stub(:save).and_return(false)
        put :update, {:id => shelf_product_info.to_param, :shelf_product_info => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested shelf_product_info" do
      shelf_product_info = ShelfProductInfo.create! valid_attributes
      expect {
        delete :destroy, {:id => shelf_product_info.to_param}, valid_session
      }.to change(ShelfProductInfo, :count).by(-1)
    end

    it "redirects to the shelf_product_infos list" do
      shelf_product_info = ShelfProductInfo.create! valid_attributes
      delete :destroy, {:id => shelf_product_info.to_param}, valid_session
      response.should redirect_to(shelf_product_infos_url)
    end
  end

end
