require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StoreProductInfosController do

  # This should return the minimal set of attributes required to create a valid
  # StoreProductInfo. As you add validations to StoreProductInfo, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {:price => 1, :quantity => 1, :product_id => 1, :store_id => 1}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StoreProductInfosController. Be sure to keep this updated too.
  def valid_session
    {:store_id => 1
    }
  end

  describe "GET index" do
    it "assigns all store_product_infos as @store_product_infos" do
      store_product_info = StoreProductInfo.create! valid_attributes
      get :index, {}
      assigns(:store_product_infos).should eq([store_product_info])
    end
  end

  describe "GET show" do
    it "assigns the requested store_product_info as @store_product_info" do
      store_product_info = StoreProductInfo.create! valid_attributes
      get :show, {:id => store_product_info.to_param}, valid_session
      assigns(:store_product_info).should eq(store_product_info)
    end
  end

  describe "GET new" do
    it "assigns a new store_product_info as @store_product_info" do
      get :new, {}, valid_session
      assigns(:store_product_info).should be_a_new(StoreProductInfo)
    end
  end

  describe "GET edit" do
    it "assigns the requested store_product_info as @store_product_info" do
      store_product_info = StoreProductInfo.create! valid_attributes
      get :edit, {:id => store_product_info.to_param}, valid_session
      assigns(:store_product_info).should eq(store_product_info)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StoreProductInfo" do
        expect {
          post :create, {:store_product_info => valid_attributes}, valid_session
        }.to change(StoreProductInfo, :count).by(1)
      end

      it "assigns a newly created store_product_info as @store_product_info" do
        post :create, {:store_product_info => valid_attributes}, valid_session
        assigns(:store_product_info).should be_a(StoreProductInfo)
        assigns(:store_product_info).should be_persisted
      end

      it "redirects to the created store_product_info" do
        post :create, {:store_product_info => valid_attributes}, valid_session
        response.should redirect_to(StoreProductInfo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved store_product_info as @store_product_info" do
        # Trigger the behavior that occurs when invalid params are submitted
        StoreProductInfo.any_instance.stub(:save).and_return(false)
        post :create, {:store_product_info => {}}, valid_session
        assigns(:store_product_info).should be_a_new(StoreProductInfo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        StoreProductInfo.any_instance.stub(:save).and_return(false)
        post :create, {:store_product_info => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested store_product_info" do
        store_product_info = StoreProductInfo.create! valid_attributes
        # Assuming there are no other store_product_infos in the database, this
        # specifies that the StoreProductInfo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        StoreProductInfo.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => store_product_info.to_param, :store_product_info => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested store_product_info as @store_product_info" do
        store_product_info = StoreProductInfo.create! valid_attributes
        put :update, {:id => store_product_info.to_param, :store_product_info => valid_attributes}, valid_session
        assigns(:store_product_info).should eq(store_product_info)
      end

      it "redirects to the store_product_info" do
        store_product_info = StoreProductInfo.create! valid_attributes
        put :update, {:id => store_product_info.to_param, :store_product_info => valid_attributes}, valid_session
        response.should redirect_to(store_product_info)
      end
    end

    describe "with invalid params" do
      it "assigns the store_product_info as @store_product_info" do
        store_product_info = StoreProductInfo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StoreProductInfo.any_instance.stub(:save).and_return(false)
        put :update, {:id => store_product_info.to_param, :store_product_info => {}}, valid_session
        assigns(:store_product_info).should eq(store_product_info)
      end

      it "re-renders the 'edit' template" do
        store_product_info = StoreProductInfo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StoreProductInfo.any_instance.stub(:save).and_return(false)
        put :update, {:id => store_product_info.to_param, :store_product_info => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested store_product_info" do
      store_product_info = StoreProductInfo.create! valid_attributes
      expect {
        delete :destroy, {:id => store_product_info.to_param}, valid_session
      }.to change(StoreProductInfo, :count).by(-1)
    end

    it "redirects to the store_product_infos list" do
      store_product_info = StoreProductInfo.create! valid_attributes
      delete :destroy, {:id => store_product_info.to_param}, valid_session
      response.should redirect_to(store_product_infos_url)
    end
  end

end
